module.exports.STATUS_UNTRACKED = '?'
module.exports.STATUS_MODIFIED = 'M'
module.exports.STATUS_ADDED = 'A'
module.exports.STATUS_UNMODIFIED = ''
module.exports.STATUS_DELETED = 'D'
module.exports.STATUS_RENAMED = 'R'
module.exports.STATUS_COPIED = 'C'
module.exports.STATUS_UNMERGED = 'U'
